# Generated by Django 6.0.3 on 2026-03-13 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_initial'),
        ('slides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_slides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slide',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='rooms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('room', 'order')},
        ),
    ]
